export type TrainingValidationData = {
  id: string;
  fullName: string;
  registrationDate: string;
  trainingName: string;
  session: string;
  validation?: "pending" | "waiting for payment" | "validated"; // for Need to be Processed
  attendance?: "present" | "absent"; // for Processed
  certificateFile?: string; // uploaded certificate file path
  notes?: string;
};

export const dummyTrainingData: TrainingValidationData[] = [
  {
    id: "ID0000001",
    fullName: "Full Name 1",
    registrationDate: "12 Feb 2025",
    trainingName: "PMP Certificate Advanced Training",
    session: "08.00-12.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
    notes: "Well prepared and submitted early.",
  },
  {
    id: "ID0000002",
    fullName: "Full Name 2",
    registrationDate: "10 Feb 2025",
    trainingName: "Agile Scrum Professional Development",
    session: "13.00-17.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
    notes: "Missing required documents.",
  },
  {
    id: "ID0000003",
    fullName: "Full Name 3",
    registrationDate: "15 Feb 2025",
    trainingName: "UI/UX Design Bootcamp for Beginners",
    session: "09.00-11.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
    notes: "Pending review.",
  },
  {
    id: "ID0000004",
    fullName: "Full Name 4",
    registrationDate: "11 Feb 2025",
    trainingName: "Introduction to Data Science with Python",
    session: "14.00-16.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
  },
  {
    id: "ID0000005",
    fullName: "Full Name 5",
    registrationDate: "08 Feb 2025",
    trainingName: "Hands-on Machine Learning Training",
    session: "10.00-12.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
  },
  {
    id: "ID0000006",
    fullName: "Full Name 6",
    registrationDate: "09 Feb 2025",
    trainingName: "Certified Scrum Master Training",
    session: "15.00-17.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
    notes: "Need to confirm payment.",
  },
  {
    id: "ID0000007",
    fullName: "Full Name 7",
    registrationDate: "13 Feb 2025",
    trainingName: "ReactJS Fundamentals and Best Practices",
    session: "13.00-15.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
    notes: "Duplicate registration.",
  },
  {
    id: "ID0000008",
    fullName: "Full Name 8",
    registrationDate: "12 Feb 2025",
    trainingName: "Cloud Computing Basics with AWS",
    session: "11.00-13.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
  },
  {
    id: "ID0000009",
    fullName: "Full Name 9",
    registrationDate: "14 Feb 2025",
    trainingName: "DevOps Tools and Automation Pipelines",
    session: "08.00-10.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
    notes: "Follow up needed.",
  },
  {
    id: "ID0000010",
    fullName: "Full Name 10",
    registrationDate: "16 Feb 2025",
    trainingName: "Cybersecurity for Business Professionals",
    session: "14.00-16.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
  },
  {
    id: "ID0000011",
    fullName: "Full Name 11",
    registrationDate: "13 Feb 2025",
    trainingName: "Advanced Product Management Workshop",
    session: "10.00-12.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
    notes: "Validated by team.",
  },
  {
    id: "ID0000012",
    fullName: "Full Name 12",
    registrationDate: "09 Feb 2025",
    trainingName: "Artificial Intelligence for Beginners",
    session: "08.00-10.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
  },
  {
    id: "ID0000013",
    fullName: "Full Name 13",
    registrationDate: "11 Feb 2025",
    trainingName: "SQL & Database Optimization Techniques",
    session: "13.00-15.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
  },
  {
    id: "ID0000014",
    fullName: "Full Name 14",
    registrationDate: "10 Feb 2025",
    trainingName: "Mobile App Development with Flutter",
    session: "10.00-12.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
    notes: "Late submission.",
  },
  {
    id: "ID0000015",
    fullName: "Full Name 15",
    registrationDate: "08 Feb 2025",
    trainingName: "Introduction to Cloud DevOps",
    session: "08.00-10.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
  },
  {
    id: "ID0000016",
    fullName: "Full Name 16",
    registrationDate: "14 Feb 2025",
    trainingName: "Data Engineering Foundations",
    session: "14.00-16.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
    notes: "Inconsistent information provided.",
  },
  {
    id: "ID0000017",
    fullName: "Full Name 17",
    registrationDate: "13 Feb 2025",
    trainingName: "Blockchain Essentials & Applications",
    session: "09.00-11.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
  },
  {
    id: "ID0000018",
    fullName: "Full Name 18",
    registrationDate: "12 Feb 2025",
    trainingName: "Data Visualization with Power BI",
    session: "11.00-13.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
  },
  {
    id: "ID0000019",
    fullName: "Full Name 19",
    registrationDate: "15 Feb 2025",
    trainingName: "Agile for Software Development Teams",
    session: "13.00-15.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
    notes: "Need to upload ID.",
  },
  {
    id: "ID0000020",
    fullName: "Full Name 20",
    registrationDate: "16 Feb 2025",
    trainingName: "Project Management in Tech Industries",
    session: "10.00-12.00",
    validation: "pending",
    attendance: undefined,
    certificateFile: undefined,
  },
];

export type CertificateValidationData = {
  id: string;
  fullName: string;
  issuedDate: string;
  trainingName: string;
  expiredDate: string;
  status?: "accepted" | "rejected";
  notes?: string;
};

export const dummyCertificateData: CertificateValidationData[] = [
  {
    id: "ID0000001",
    fullName: "Full Name 1",
    issuedDate: "20 Nov 2024",
    trainingName: "PMP Certificate Advanced Training",
    expiredDate: "20 Nov 2026",
    status: "accepted",
    notes: "Issued after training completion.",
  },
  {
    id: "ID0000002",
    fullName: "Full Name 2",
    issuedDate: "10 Oct 2024",
    trainingName: "Agile Scrum Professional Development",
    expiredDate: "10 Oct 2026",
    status: "rejected",
    notes: "Mismatch in name.",
  },
  {
    id: "ID0000003",
    fullName: "Full Name 3",
    issuedDate: "15 Sep 2024",
    trainingName: "UI/UX Design Bootcamp for Beginners",
    expiredDate: "15 Sep 2026",
    notes: "Pending issuer confirmation.",
  },
  {
    id: "ID0000004",
    fullName: "Full Name 4",
    issuedDate: "11 Aug 2024",
    trainingName: "Introduction to Data Science with Python",
    expiredDate: "11 Aug 2026",
  },
  {
    id: "ID0000005",
    fullName: "Full Name 5",
    issuedDate: "01 Sep 2024",
    trainingName: "Comprehensive Java Programming Certificate",
    expiredDate: "01 Sep 2026",
    status: "accepted",
  },
  {
    id: "ID0000006",
    fullName: "Full Name 6",
    issuedDate: "22 Oct 2024",
    trainingName: "Machine Learning & AI for Professionals",
    expiredDate: "22 Oct 2026",
  },
  {
    id: "ID0000007",
    fullName: "Full Name 7",
    issuedDate: "05 Nov 2024",
    trainingName: "Cybersecurity Basics and Network Defense",
    expiredDate: "05 Nov 2026",
    status: "rejected",
    notes: "Certificate expired during review.",
  },
  {
    id: "ID0000008",
    fullName: "Full Name 8",
    issuedDate: "19 Sep 2024",
    trainingName: "Digital Marketing & SEO Fundamentals",
    expiredDate: "19 Sep 2026",
  },
  {
    id: "ID0000009",
    fullName: "Full Name 9",
    issuedDate: "28 Aug 2024",
    trainingName: "DevOps Practices and Cloud CI/CD Pipelines",
    expiredDate: "28 Aug 2026",
    status: "accepted",
    notes: "Reviewed by admin.",
  },
  {
    id: "ID0000010",
    fullName: "Full Name 10",
    issuedDate: "07 Oct 2024",
    trainingName: "Blockchain Essentials & Smart Contracts",
    expiredDate: "07 Oct 2026",
  },
  {
    id: "ID0000011",
    fullName: "Full Name 11",
    issuedDate: "12 Sep 2024",
    trainingName: "React Front-End Development Masterclass",
    expiredDate: "12 Sep 2026",
    status: "accepted",
  },
  {
    id: "ID0000012",
    fullName: "Full Name 12",
    issuedDate: "30 Jul 2024",
    trainingName: "Cloud Computing with AWS and Azure",
    expiredDate: "30 Jul 2026",
  },
  {
    id: "ID0000013",
    fullName: "Full Name 13",
    issuedDate: "09 Oct 2024",
    trainingName: "Scrum Master Certification Program",
    expiredDate: "09 Oct 2026",
    status: "rejected",
  },
  {
    id: "ID0000014",
    fullName: "Full Name 14",
    issuedDate: "18 Sep 2024",
    trainingName: "Advanced SQL & Database Design Training",
    expiredDate: "18 Sep 2026",
    notes: "Data mismatch found.",
  },
  {
    id: "ID0000015",
    fullName: "Full Name 15",
    issuedDate: "25 Oct 2024",
    trainingName: "Python for Data Analysis & Visualization",
    expiredDate: "25 Oct 2026",
  },
  {
    id: "ID0000016",
    fullName: "Full Name 16",
    issuedDate: "14 Aug 2024",
    trainingName: "ITIL Foundation Certification Training",
    expiredDate: "14 Aug 2026",
    status: "accepted",
  },
  {
    id: "ID0000017",
    fullName: "Full Name 17",
    issuedDate: "03 Nov 2024",
    trainingName: "Mobile App Development with Flutter",
    expiredDate: "03 Nov 2026",
  },
  {
    id: "ID0000018",
    fullName: "Full Name 18",
    issuedDate: "22 Jul 2024",
    trainingName: "Big Data Processing using Apache Spark",
    expiredDate: "22 Jul 2026",
    status: "rejected",
  },
  {
    id: "ID0000019",
    fullName: "Full Name 19",
    issuedDate: "29 Sep 2024",
    trainingName: "Business Intelligence and Power BI",
    expiredDate: "29 Sep 2026",
    notes: "Certificate under review.",
  },
  {
    id: "ID0000020",
    fullName: "Full Name 20",
    issuedDate: "16 Oct 2024",
    trainingName: "Kubernetes Administration Certification",
    expiredDate: "16 Oct 2026",
    status: "accepted",
  },
];